### PR TITLE
chore: Remove instances of deny(warnings) annotation

### PR DESCRIPTION
**Pull request by robert-monk**
Remove the deny(warnings) annotations as mentioned in #36. Only found the annotation in synth and synth-core.

### CODE REVIEW

**Comment by llogiq** [comment]
Thanks for opening this pull request. However, we'd still like to fail our CI actions if any warnings occur. So to make this complete, you should look into all github actions that call `cargo` and add an `-D warnings` to each of them.

**Comment by llogiq** [comment]
@robert-monk sorry for letting you wait, do you need anything from my side to follow this through?

**Comment by robert-monk** [comment]
@llogiq everything is ok, just getting to it now, sorry!

**Comment by llogiq** [comment]
Great! Thank you for seeing this through. 👍

**Comment by llogiq** [comment]
Error seems a flaky test, which is certainly unrelated. Weird, I thought I had removed all indeterminism. Thank you for helping our project! :heart:

**Pull request merged**
