### PR TITLE
Feature: synth init <directory-name>

### PR DESCRIPTION
**Pull request by baile320**
Hi, opening a PR for: https://github.com/getsynth/synth/issues/46.

I wasn't very familiar with this package or some of the crates used, so let me know if you have any feedback... thank you!

### CODE REVIEW

**Comment by christoshadjiaslanis** [comment]
Thanks for this! Will review soon :)

**Comment by baile320** [comment]
I'm trying to figure out why the tests failed, and I'm not entirely sure why the synth-bench test failed, or what the failure message "Error: cannot create comment" means. If you have any thoughts/suggestions, I'd be happy to look into them!

**Comment by christoshadjiaslanis** [comment]
Hey! 

> I'm trying to figure out why the tests failed, and I'm not entirely sure why the synth-bench test failed, or what the failure message "Error: cannot create comment" means. If you have any thoughts/suggestions, I'd be happy to look into them!

Don't worry about this. We use a github action to comment on the PR and I think it is broken from under us. As long as the tests pass we're a-ok.

I'll review now btw.

**Review by christoshadjiaslanis — COMMENTED** [review]
This looks great! 

I tested it out a bit as well. It works with:

1. relative path (synth init a/)
2. absolute path (synth init /home/christos/a)
3. creating subdirectories where need  (synth init i_dont_exist/workspace)
4. existing directories (synth init i_exist/)

Great stuff!

**Pull request merged**
